#!/usr/bin/perl

use strict;
use warnings;
use Cwd;
use Youri::Package::RPM;
use Git;
use YAML::XS;
use HTTP::SimpleLinkChecker qw(check_link);
use Digest::SHA1;
use LWP::Simple qw(getstore is_error);

=head1 NAME

bfc - ABF command-line client

=head1 SYNOPSIS

bfc <action> [options]

=head2 Actions:

=over 8

=item f[etch]

fetch new sources from upstream

=item g[et]

get all sources for local build

=item s[ync]

sync sources and patches

=back

=head1 DESCRIPTION

Build farm client is an alternative ABF client. It helps managing git repos
and ABF tasks.

=head1 COPYRIGHT

Copyright (C) 2012, Dmitry Mikhirev

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see L<http://www.gnu.org/licenses/>.

=cut

my $action = shift @ARGV;

for ($action) {
    /^f(etch)?$/        ?       fetch(@ARGV)    :
    /^g(et)?$/          ?       get(@ARGV)      :
    /^s(ync)?$/         ?       sync(@ARGV)     :
    die "wrong syntax\n";
}

sub fetch {
    my $spec = init_spec();
    my $abfyml = read_abfyml();

    my @sourceurls = ($spec->sources_url(), $spec->icon_url());
    @sourceurls = map { m/^(https?|ftp):/ ? $_ : () } @sourceurls;

    foreach (@sourceurls) {
        m([^/]+$);
        unless (-f $& or
            $abfyml->{sources}{$&} and checkfilestore($abfyml->{sources}{$&}))
        {
            print "$&\n";
            download($_, $&);
        }
    }
}

sub get {
    my $spec = init_spec();
    my $abfyml = read_abfyml();
    my @sourceurls = ($spec->sources_url(), $spec->icon_url());

    foreach (@sourceurls) {
        m([^/]+$);
        unless (-f $&) {
            print "$&\n";
            if (my $sha1 = $abfyml->{sources}{$&}) {
                download("http://file-store.rosalinux.ru/download/$sha1", $&);
            } else {
                download($_, $&);
            }
        }
    }
}

sub sync {
    my $specfile = find_spec();
    my $spec = init_spec($specfile);
    my @sources = ($specfile, $spec->sources(), $spec->icon());
    my $git = Git->repository(cwd())
        or die "Not in the git working directory\n";
    my @trackedfiles = split /\n/, $git->command('ls-files');
    my @filestoupload;
    my $abfyml = read_abfyml();

    if ($abfyml) {
        foreach my $file (keys %{$abfyml->{sources}}) {
            if ($file ~~ @sources) {
                unless (checkfilestore($abfyml->{sources}{$file})) {
                    push @filestoupload, $file;
                }
            } else {
                delete $abfyml->{sources}{$file};
            }
        }
    }

    foreach my $file (@sources) {
        unless ($abfyml->{sources}{$file}) {
            if (-f $file) {
                if (-T _) {
                    unless ($file ~~ @trackedfiles) {
                        $git->command('add', $file);
                        print "$file added\n";
                    }
                } else {
                    my $ctx = Digest::SHA1->new();
                    open(my $FILE, "<", $file);
                    $ctx->addfile($FILE);
                    $abfyml->{sources}{$file} = $ctx->hexdigest();
                    unless (checkfilestore($abfyml->{sources}{$file})) {
                        push @filestoupload, $file;
                    }
                }
            } else {
                print STDERR "No such file: $file\n";
            }
        }
    }

    YAML::XS::DumpFile('.abf.yml', $abfyml);

    unless ('.abf.yml' ~~ @trackedfiles) {
        $git->command('add', '.abf.yml') and print "added .abf.yml\n";
    }
    push @sources, '.abf.yml';

    foreach my $file (@trackedfiles) {
        if ($file ~~ @sources) {
            if ($abfyml->{sources}{$file}) {
                $git->command('rm', '--cached', $file);
                print "$file removed from git index\n";
            }
        } else {
            $git->command('rm', $file);
            print "$file removed\n";
        }
    }

    if (@filestoupload) {
        print "\nYou need to upload following files to file store:\n";
        print join("\n", @filestoupload) . "\n";
    }
}

sub checkfilestore {
    my ($sha1) = @_ or return;
    my $url = "http://file-store.rosalinux.ru/download/$sha1";
    my $status = check_link($url);
    if ($status == 404) {
        return 0;
    } elsif ($status == 200) {
        return 1;
    } else {
        print STDERR "Warning: requesting $url failed\n";
        print STDERR "HTTP response: $status: $HTTP::SimpleLinkChecker::ERROR\n";
        return -1;
    }
 
}

sub find_spec {
    my ($specfile) = <*.spec>
        or die "Can't find any spec file\n";
    return $specfile;
}

sub init_spec {
    my ($specfile) = @_ ? @_ : (find_spec());
    my $rpm_class = Youri::Package::RPM->get_wrapper_class();
    set_rpm_dirs();
    my $spec = $rpm_class->new_spec($specfile, anyarch => 1, force => 1)
        or die "Can't parse spec file $specfile\n";
    return $spec;
}

sub read_abfyml {
    my $abfyml;
    if (-f '.abf.yml') {
        $abfyml = YAML::XS::LoadFile('.abf.yml');
    }
    return $abfyml;
}

sub set_rpm_dirs {
    my $rpm_class = Youri::Package::RPM->get_wrapper_class();
    foreach ("_sourcedir", "_specdir") {
        $rpm_class->add_macro("$_ " . cwd());
    }
}

sub download {
    my ($url, $file) = @_;
    my $result = getstore($url, $file);
    if (is_error($result)) {
        print STDERR "Can't download $_: server returned $result.\n";
    }
}
